name: Deploy Node Application

on:
  push:
    branches:
      - main
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t jamshaidkhalid/bitwalee-be .

      - name: Tag Docker image
        run: docker push jamshaidkhalid/bitwalee-be:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull jamshaidkhalid/bitwalee-be:latest
      - name: Delete existing container
        run: docker rm -f bitwalee-container-5
      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name bitwalee-container-5 -e MONGO_URI=`${{secrets.MONGO_URI}}` jamshaidkhalid/bitwalee-be:latest
      
